export const dasboardModel = [
    {id:1,name:'Best Dish', img:'/assets/images/icons/dashboard/best_dish.jpg'},
    {id:2,name:'Top 10', img:'/assets/images/icons/dashboard/top10.jpg'},
    {id:3,name:'Tiffin Box', img:'/assets/images/icons/dashboard/tiffin.jpg'},
    {id:4,name:'Table Booking', img:'/assets/images/icons/dashboard/table_book.jpg'},
    {id:5,name:'Resto Chat', img:'/assets/images/icons/dashboard/chat1.jpg'},
    {id:6,name:'Order Online', img:'/assets/images/icons/dashboard/deliver.jpg'},
    {id:7,name:'Dairy', img:'/assets/images/icons/dashboard/diary.jpg'},
    {id:8,name:'Wallets', img:'/assets/images/icons/dashboard/wallet.jpg'},
    {id:9,name:'FeedBack', img:'/assets/images/icons/dashboard/feedBack.jpg'},
    {id:10,name:'Friends', img:'/assets/images/icons/dashboard/friends.jpg'},
    {id:11,name:'Food Marshal', img:'/assets/images/icons/dashboard/food_marshal.jpg'},
    {id:12,name:'Events', img:'/assets/images/icons/dashboard/events.jpg'},
    {id:13,name:'Map It', img:'/assets/images/icons/dashboard/map.jpg'},
    {id:14,name:'Search', img:'/assets/images/icons/dashboard/search.jpg'},
    {id:15,name:'Change City', img:'/assets/images/icons/dashboard/change_city.jpg'},
    {id:16,name:'Pledge', img:'/assets/images/icons/dashboard/pledge.jpg'},
    {id:17,name:'Share', img:'/assets/images/icons/dashboard/share.jpg'},
    {id:15,name:'My Profile', img:'/assets/images/icons/dashboard/user.jpg'},
    {id:16,name:'Contact Us', img:'/assets/images/icons/dashboard/contact_us.jpg'},
    {id:17,name:'Merchant Login', img:'/assets/images/icons/dashboard/merchant.jpg'},
    
]