export const dasboardModel = [
    {id:1,route:'/home/restraunts',name:'Best Dish', img:'/assets/images/icons/dashboard/best_dish.jpg'},
    {id:2,route:'/',name:'Top 10', img:'/assets/images/icons/dashboard/top10.jpg'},
    {id:3,route:'/',name:'Tiffin Box', img:'/assets/images/icons/dashboard/tiffin.jpg'},
    {id:4,route:'/',name:'Table Booking', img:'/assets/images/icons/dashboard/table_book.jpg'},
    {id:5,route:'/',name:'Resto Chat', img:'/assets/images/icons/dashboard/chat1.jpg'},
    {id:6,route:'/',name:'Order Online', img:'/assets/images/icons/dashboard/deliver.jpg'},
    {id:7,route:'/',name:'Dairy', img:'/assets/images/icons/dashboard/diary.jpg'},
    {id:8,route:'/',name:'Wallets', img:'/assets/images/icons/dashboard/wallet.jpg'},
    {id:9,route:'/',name:'FeedBack', img:'/assets/images/icons/dashboard/feedBack.jpg'},
    {id:10,route:'/',name:'Friends', img:'/assets/images/icons/dashboard/friends.jpg'},
    {id:11,route:'/',name:'Food Marshal', img:'/assets/images/icons/dashboard/food_marshal.jpg'},
    {id:12,route:'/',name:'Events', img:'/assets/images/icons/dashboard/events.jpg'},
    {id:13,route:'/',name:'Map It', img:'/assets/images/icons/dashboard/map.jpg'},
    {id:14,route:'/',name:'Search', img:'/assets/images/icons/dashboard/search.jpg'},
    {id:15,route:'/',name:'Change City', img:'/assets/images/icons/dashboard/change_city.jpg'},
    {id:16,route:'/',name:'Pledge', img:'/assets/images/icons/dashboard/pledge.jpg'},
    {id:17,route:'/',name:'Share', img:'/assets/images/icons/dashboard/share.jpg'},
    {id:15,route:'/',name:'My Profile', img:'/assets/images/icons/dashboard/user.jpg'},
    {id:16,route:'/',name:'Contact Us', img:'/assets/images/icons/dashboard/contact_us.jpg'},
    {id:17,route:'/merchants',name:'Merchant Login', img:'/assets/images/icons/dashboard/merchant.jpg'},
    
]